package:
  name: "crypto_feature_preprocess"
  version: '0.2.0'
about:
  summary: "This is crypto preprocess feature Python library"
source:
  path: ..
requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python
    - pandas>=1.5.2
    - pyarrow>=5.0.0
    - pydantic>=1.10.2
    - cachetools==4.2.2
    - s3fs>=2023.3.0
    - cryptomarketdata
    #- SQLAlchemy==2.0.4
    #- pydash==5.0.2
    #- psycopg2==2.9.3
    
