package:
  name: "cryptomarketdata"
  version: '0.1.1'
about:
  summary: "This is crypto market data operation Python library"
source:
  path: ..
requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python
    - SQLAlchemy==2.0.4
    - pandas>=1.5.2
    - pyarrow>=5.0.0
    - pydash==5.0.2
    - pydantic>=1.10.2
    - psycopg2==2.9.3
    - cachetools==4.2.2
    - cryptomarketdata
